#put your bot token below to use your bot on your server
#your bot sould only be connected to one server for this to work
Bot:
  token: ''
#name of your main channel. just used to confirm the bot is connected
Channel: ''